# Generated by Django 5.2.10 on 2026-01-30 22:35

import django.db.models.deletion
import simple_history.models
import taggit.managers
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('priority', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Listing',
                'verbose_name_plural': 'Listings',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='offerman.collection')),
            ],
            options={
                'verbose_name': 'Collection',
                'verbose_name_plural': 'Collections',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalProduct',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('sku', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(default='un', help_text='un, kg, lt, etc.', max_length=20)),
                ('base_price_q', models.BigIntegerField(default=0, help_text='Base price in cents')),
                ('availability_policy', models.CharField(choices=[('stock_only', 'Stock only'), ('planned_ok', 'Accepts planned'), ('demand_ok', 'Accepts demand')], default='planned_ok', max_length=20)),
                ('reference_cost_q', models.BigIntegerField(blank=True, help_text='Production cost in cents (ref. Craftsman)', null=True)),
                ('shelflife', models.IntegerField(blank=True, help_text='Shelf life in days. None=non-perishable, 0=same day only', null=True)),
                ('is_visible', models.BooleanField(db_index=True, default=True, help_text='Show in catalog (False = hidden/discontinued)')),
                ('is_sellable', models.BooleanField(db_index=True, default=True, help_text='Can be purchased (False = ingredient or paused)')),
                ('is_batch_produced', models.BooleanField(default=False, help_text='Produced in batches (for Craftsman)')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Product',
                'verbose_name_plural': 'historical Products',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sku', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(default='un', help_text='un, kg, lt, etc.', max_length=20)),
                ('base_price_q', models.BigIntegerField(default=0, help_text='Base price in cents')),
                ('availability_policy', models.CharField(choices=[('stock_only', 'Stock only'), ('planned_ok', 'Accepts planned'), ('demand_ok', 'Accepts demand')], default='planned_ok', max_length=20)),
                ('reference_cost_q', models.BigIntegerField(blank=True, help_text='Production cost in cents (ref. Craftsman)', null=True)),
                ('shelflife', models.IntegerField(blank=True, help_text='Shelf life in days. None=non-perishable, 0=same day only', null=True)),
                ('is_visible', models.BooleanField(db_index=True, default=True, help_text='Show in catalog (False = hidden/discontinued)')),
                ('is_sellable', models.BooleanField(db_index=True, default=True, help_text='Can be purchased (False = ingredient or paused)')),
                ('is_batch_produced', models.BooleanField(default=False, help_text='Produced in batches (for Craftsman)')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('keywords', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ListingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_q', models.BigIntegerField(help_text='Price in cents')),
                ('min_qty', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=10)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_sellable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='offerman.listing')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_items', to='offerman.product')),
            ],
            options={
                'verbose_name': 'Listing Item',
                'verbose_name_plural': 'Listing Items',
                'ordering': ['listing', 'product__name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalListingItem',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('price_q', models.BigIntegerField(help_text='Price in cents')),
                ('min_qty', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=10)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_sellable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='offerman.listing')),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='offerman.product')),
            ],
            options={
                'verbose_name': 'historical Listing Item',
                'verbose_name_plural': 'historical Listing Items',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='CollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, help_text='Primary collection for this product')),
                ('sort_order', models.IntegerField(default=0)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='offerman.collection')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to='offerman.product')),
            ],
            options={
                'verbose_name': 'Collection Item',
                'verbose_name_plural': 'Collection Items',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=10)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_bundles', to='offerman.product')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='offerman.product')),
            ],
            options={
                'verbose_name': 'Product Component',
                'verbose_name_plural': 'Product Components',
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='offerman_pr_sku_b30edb_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_visible', 'is_sellable'], name='offerman_pr_is_visi_a97838_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='listingitem',
            unique_together={('listing', 'product', 'min_qty')},
        ),
        migrations.AlterUniqueTogether(
            name='collectionitem',
            unique_together={('collection', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='productcomponent',
            unique_together={('parent', 'component')},
        ),
    ]
