# Generated by Django 5.0.3 on 2026-01-31 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='short_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
