# Generated by Django 5.0.3 on 2026-01-31 00:49

import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerman', '0002_add_short_description'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalproduct',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical produto', 'verbose_name_plural': 'historical produtos'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'produto', 'verbose_name_plural': 'produtos'},
        ),
        migrations.RenameField(
            model_name='historicalproduct',
            old_name='description',
            new_name='long_description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='long_description',
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='long_description',
            field=models.TextField(blank=True, help_text='Descrição completa do produto', verbose_name='descrição longa'),
        ),
        migrations.AlterField(
            model_name='product',
            name='long_description',
            field=models.TextField(blank=True, help_text='Descrição completa do produto', verbose_name='descrição longa'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='availability_policy',
            field=models.CharField(choices=[('stock_only', 'Somente estoque'), ('planned_ok', 'Aceita planejado'), ('demand_ok', 'Aceita demanda')], default='planned_ok', max_length=20, verbose_name='política de disponibilidade'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='base_price_q',
            field=models.BigIntegerField(default=0, help_text='Preço base em centavos', verbose_name='preço base'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='is_batch_produced',
            field=models.BooleanField(default=False, help_text='Produzido em lotes (para Craftsman)', verbose_name='produção em lote'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='is_sellable',
            field=models.BooleanField(db_index=True, default=True, help_text='Pode ser vendido (Não = insumo ou pausado)', verbose_name='vendável'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='is_visible',
            field=models.BooleanField(db_index=True, default=True, help_text='Exibir no catálogo (Não = oculto/descontinuado)', verbose_name='visível'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='metadados'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='name',
            field=models.CharField(max_length=200, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='reference_cost_q',
            field=models.BigIntegerField(blank=True, help_text='Custo de produção em centavos (ref. Craftsman)', null=True, verbose_name='custo de referência'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='shelflife',
            field=models.IntegerField(blank=True, help_text='Validade em dias. Vazio=não perecível, 0=somente no dia', null=True, verbose_name='validade'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='short_description',
            field=models.CharField(blank=True, help_text='Descrição resumida para listagens (máx. 255 caracteres)', max_length=255, verbose_name='descrição curta'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='sku',
            field=models.CharField(db_index=True, max_length=100, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='unit',
            field=models.CharField(default='un', help_text='un, kg, lt, etc.', max_length=20, verbose_name='unidade'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='atualizado em'),
        ),
        migrations.AlterField(
            model_name='product',
            name='availability_policy',
            field=models.CharField(choices=[('stock_only', 'Somente estoque'), ('planned_ok', 'Aceita planejado'), ('demand_ok', 'Aceita demanda')], default='planned_ok', max_length=20, verbose_name='política de disponibilidade'),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_price_q',
            field=models.BigIntegerField(default=0, help_text='Preço base em centavos', verbose_name='preço base'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_batch_produced',
            field=models.BooleanField(default=False, help_text='Produzido em lotes (para Craftsman)', verbose_name='produção em lote'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_sellable',
            field=models.BooleanField(db_index=True, default=True, help_text='Pode ser vendido (Não = insumo ou pausado)', verbose_name='vendável'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_visible',
            field=models.BooleanField(db_index=True, default=True, help_text='Exibir no catálogo (Não = oculto/descontinuado)', verbose_name='visível'),
        ),
        migrations.AlterField(
            model_name='product',
            name='keywords',
            field=taggit.managers.TaggableManager(blank=True, help_text='Tags para SEO e busca. Separe por vírgula.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='palavras-chave'),
        ),
        migrations.AlterField(
            model_name='product',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='metadados'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='product',
            name='reference_cost_q',
            field=models.BigIntegerField(blank=True, help_text='Custo de produção em centavos (ref. Craftsman)', null=True, verbose_name='custo de referência'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shelflife',
            field=models.IntegerField(blank=True, help_text='Validade em dias. Vazio=não perecível, 0=somente no dia', null=True, verbose_name='validade'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, help_text='Descrição resumida para listagens (máx. 255 caracteres)', max_length=255, verbose_name='descrição curta'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(default='un', help_text='un, kg, lt, etc.', max_length=20, verbose_name='unidade'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='atualizado em'),
        ),
    ]
