# Generated by Django 5.2.11 on 2026-02-21 16:09

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerman', '0004_rename_visibility_fields'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Coleção', 'verbose_name_plural': 'Coleções'},
        ),
        migrations.AlterModelOptions(
            name='collectionitem',
            options={'ordering': ['sort_order'], 'verbose_name': 'Item de Coleção', 'verbose_name_plural': 'Itens de Coleção'},
        ),
        migrations.AlterModelOptions(
            name='historicallistingitem',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Item de Listagem', 'verbose_name_plural': 'historical Itens de Listagem'},
        ),
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['-priority', 'name'], 'verbose_name': 'Listagem', 'verbose_name_plural': 'Listagens'},
        ),
        migrations.AlterModelOptions(
            name='listingitem',
            options={'ordering': ['listing', 'product__name'], 'verbose_name': 'Item de Listagem', 'verbose_name_plural': 'Itens de Listagem'},
        ),
        migrations.AlterModelOptions(
            name='productcomponent',
            options={'verbose_name': 'Componente de Produto', 'verbose_name_plural': 'Componentes de Produto'},
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='offerman_pr_is_visi_a97838_idx',
        ),
        migrations.AlterField(
            model_name='collection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.TextField(blank=True, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='ativo'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='offerman.collection', verbose_name='coleção pai'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='ordem'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='atualizado em'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='valid_from',
            field=models.DateField(blank=True, null=True, verbose_name='válido de'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='valid_until',
            field=models.DateField(blank=True, null=True, verbose_name='válido até'),
        ),
        migrations.AlterField(
            model_name='collectionitem',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='offerman.collection', verbose_name='coleção'),
        ),
        migrations.AlterField(
            model_name='collectionitem',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Coleção principal para este produto', verbose_name='principal'),
        ),
        migrations.AlterField(
            model_name='collectionitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to='offerman.product', verbose_name='produto'),
        ),
        migrations.AlterField(
            model_name='collectionitem',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='ordem'),
        ),
        migrations.AlterField(
            model_name='historicallistingitem',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='historicallistingitem',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='disponível'),
        ),
        migrations.AlterField(
            model_name='historicallistingitem',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='publicado'),
        ),
        migrations.AlterField(
            model_name='historicallistingitem',
            name='listing',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='offerman.listing', verbose_name='listagem'),
        ),
        migrations.AlterField(
            model_name='historicallistingitem',
            name='min_qty',
            field=models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=10, verbose_name='quantidade mínima'),
        ),
        migrations.AlterField(
            model_name='historicallistingitem',
            name='price_q',
            field=models.BigIntegerField(help_text='Preço em centavos', verbose_name='preço'),
        ),
        migrations.AlterField(
            model_name='historicallistingitem',
            name='product',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='offerman.product', verbose_name='produto'),
        ),
        migrations.AlterField(
            model_name='historicallistingitem',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='atualizado em'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='is_available',
            field=models.BooleanField(db_index=True, default=True, help_text='Disponível para venda (Não = insumo ou pausado)', verbose_name='disponível'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True, help_text='Publicado no catálogo (Não = oculto/descontinuado)', verbose_name='publicado'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='code',
            field=models.SlugField(unique=True, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(blank=True, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='ativo'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='prioridade'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='atualizado em'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='valid_from',
            field=models.DateField(blank=True, null=True, verbose_name='válido de'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='valid_until',
            field=models.DateField(blank=True, null=True, verbose_name='válido até'),
        ),
        migrations.AlterField(
            model_name='listingitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='listingitem',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='disponível'),
        ),
        migrations.AlterField(
            model_name='listingitem',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='publicado'),
        ),
        migrations.AlterField(
            model_name='listingitem',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='offerman.listing', verbose_name='listagem'),
        ),
        migrations.AlterField(
            model_name='listingitem',
            name='min_qty',
            field=models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=10, verbose_name='quantidade mínima'),
        ),
        migrations.AlterField(
            model_name='listingitem',
            name='price_q',
            field=models.BigIntegerField(help_text='Preço em centavos', verbose_name='preço'),
        ),
        migrations.AlterField(
            model_name='listingitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_items', to='offerman.product', verbose_name='produto'),
        ),
        migrations.AlterField(
            model_name='listingitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='atualizado em'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(db_index=True, default=True, help_text='Disponível para venda (Não = insumo ou pausado)', verbose_name='disponível'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True, help_text='Publicado no catálogo (Não = oculto/descontinuado)', verbose_name='publicado'),
        ),
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='productcomponent',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_bundles', to='offerman.product', verbose_name='componente'),
        ),
        migrations.AlterField(
            model_name='productcomponent',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='offerman.product', verbose_name='produto pai'),
        ),
        migrations.AlterField(
            model_name='productcomponent',
            name='qty',
            field=models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=10, verbose_name='quantidade'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_published', 'is_available'], name='offerman_pr_is_publ_f149e2_idx'),
        ),
    ]
